include: package:all_lint_rules_community/all.yaml

# REST OF YOUR ANALYSIS_OPTIONS.YAML FILE
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/.test_coverage.dart"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    # Without ignore here, we cause import of all_lint_rules to warn, because some rules conflict.
    # We explicitly enabled even conflicting rules and are fixing the conflicts in this file.
    included_file_warning: ignore
    # Treat missing required parameters as an error.
    missing_required_param: error
    # Treat missing returns as an error, not as a hint or a warning.
    missing_return: error
    # Don't assign new values to parameters of methods or functions.
    # Treat assigning new values to a parameter as a warning. We would almost like to set this
    parameter_assignments: warning

linter:
  rules:
    public_member_api_docs: false
    prefer_final_parameters: false
    prefer_double_quotes: false
    always_specify_types: false
    prefer_relative_imports: false
    prefer_expression_function_bodies: false
    unnecessary_final: false
    depend_on_referenced_packages: false
